export const ONBOARDING_SCREENS = [
  {
    id: 1,
    title: "Walk Home With Confidence.",
    subtitle: "Welcome to Gabay",
    description: "Whether you're heading home after school, work, or a late-night commute, Gabay helps guide every step with safer routes and trusted navigation.",
    cta: "Get Started",
    brandLine: "Your Guide Home, Every Step of the Way.",
    illustration: "welcome",
  },
  {
    id: 2,
    title: "Not Just the Fastest Route—The Safer One.",
    subtitle: "Choose Safer Paths",
    description: "Discover routes that help you avoid reported hazards while highlighting Safe Havens, police stations, hospitals, and other trusted places nearby.",
    cta: "Next",
    brandLine: "Safe Routes. Safer Nights.",
    illustration: "safe-routes",
  },
  {
    id: 3,
    title: "Stay Connected When It Matters Most.",
    subtitle: "You're Never Walking Alone",
    description: "Share your live location with trusted contacts, quickly access emergency services, and let your loved ones know you're safe throughout your journey.",
    cta: "Next",
    brandLine: "Never Walk Alone Again.",
    illustration: "connected",
  },
  {
    id: 4,
    title: "Help Others Stay Safe.",
    subtitle: "A Safer Community Starts With You",
    description: "Report hazards, update community safety information, and contribute to a safer journey for everyone using Gabay.",
    cta: "Start My Safe Journey",
    secondaryCta: "Skip",
    brandLine: "Wherever You're Going, Gabay Goes With You.",
    illustration: "community",
  },
];
